#include <math.h>
#include <stdio.h>

double pmelt_T_iceIh(double T);
double pmelt_T_iceIII(double T);
double pmelt_T_iceV(double T);
double pmelt_T_iceVI(double T);
double pmelt_T_iceVII(double T);
double psubl_T(double T);
double B23p_T(double T);
double B23T_p(double p);
double p3sat_h(double h);
double p3sat_s(double s);
double hB13_s(double s);
double TB23_hs(double h, double s);
double v1_pT(double p, double T);
double h1_pT(double p, double T);
double u1_pT(double p, double T);
double s1_pT(double p, double T);
double Cp1_pT(double p, double T);
double Cv1_pT(double p, double T);
double w1_pT(double p, double T);
double T1_ph(double p, double h);
double T1_ps(double p, double s);
double p1_hs(double h, double s);
double T1_prho(double p, double rho);
double v2_pT(double p, double T);
double h2_pT(double p, double T);
double u2_pT(double p, double T);
double s2_pT(double p, double T);
double Cp2_pT(double p, double T);
double Cv2_pT(double p, double T);
double w2_pT(double p, double T);
double T2_ph(double p, double h);
double T2_ps(double p, double s);
double p2_hs(double h, double s);
double T2_prho(double p, double rho);
double p3_rhoT(double rho, double T);
double u3_rhoT(double rho, double T);
double h3_rhoT(double rho, double T);
double s3_rhoT(double rho, double T);
double Cp3_rhoT(double rho, double T);
double Cv3_rhoT(double rho, double T);
double w3_rhoT(double rho, double T);
double T3_ph(double p, double h);
double v3_ph(double p, double h);
double T3_ps(double p, double s);
double v3_ps(double p, double s);
double p3_hs(double h, double s);
double h3_pT(double p, double T);
double T3_prho(double p, double rho);
double p4_T(double T);
double T4_p(double p);
double h4_s(double s);
double p4_s(double s);
double h4L_p(double p);
double h4V_p(double p);
double x4_ph(double p, double h);
double x4_ps(double p, double s);
double T4_hs(double h, double s);
double h5_pT(double p, double T);
double v5_pT(double p, double T);
double u5_pT(double p, double T);
double Cp5_pT(double p, double T);
double s5_pT(double p, double T);
double Cv5_pT(double p, double T);
double w5_pT(double p, double T);
double T5_ph(double p, double h);
double T5_ps(double p, double s);
double T5_prho(double p, double rho);
int region_pT(double p, double T);
int region_ph(double p, double h);
int region_ps(double p, double s);
int region_hs(double h, double s);
int region_prho(double p, double rho);
double my_AllRegions_pT(double p, double T);
double my_AllRegions_ph(double p, double h);
double tc_ptrho(float p, float T, float rho);
double Surface_Tension_T(double T);
double tsat_p(double p);
double tsat_s(double s);
double t_ph(double p, double h);
double t_ps(double p, double s);
double t_hs(double h, double s);
double psat_s(double s);
double psat_t(double t);
double p_hs(double h, double s);
double p_hrho(double h, double rho);
double hV_p(double p);
double hL_p(double p);
double hV_t(double t);
double hL_t(double t);
double h_pt(double p, double t);
double h_ps(double p, double s);
double h_px(double p, double x);
double h_prho(double p, double rho);
double h_tx(double t, double x);
double vV_p(double p);
double vL_p(double p);
double vV_t(double t);
double vL_t(double t);
double v_pt(double p, double t);
double v_ph(double p, double h);
double v_ps(double p, double s);
double rhoV_p(double p);
double rhoL_p(double p);
double rhoV_t(double t);
double rhoL_t(double t);
double rho_pt(double p, double t);
double rho_ph(double p, double h);
double rho_ps(double p, double s);
double sV_p(double p);
double sL_p(double p);
double sV_t(double t);
double sL_t(double t);
double s_pt(double p, double t);
double s_ph(double p, double h);
double uV_p(double p);
double uL_p(double p);
double uV_t(double t);
double uL_t(double t);
double u_pt(double p, double t);
double u_ph(double p, double h);
double u_ps(double p, double s);
double CpV_p(double p);
double CpL_p(double p);
double CpV_t(double t);
double CpL_t(double t);
double Cp_pt(double p, double t);
double Cp_ph(double p, double h);
double Cp_ps(double p, double s);
double CvV_p(double p);
double CvL_p(double p);
double CvV_t(double t);
double CvL_t(double t);
double Cv_pt(double p, double t);
double Cv_ph(double p, double h);
double Cv_ps(double p, double s);
double wV_p(double p);
double wL_p(double p);
double wV_t(double t);
double wL_t(double t);
double w_pt(double p, double t);
double w_ph(double p, double h);
double w_ps(double p, double s);
double my_pt(double p, double t);
double my_ph(double p, double h);
double my_ps(double p, double s);
double pr_pt(double p, double t);
double pr_ph(double p, double h);
double st_t(double t);
double st_p(double p);
double tcL_p(double p);
double tcV_p(double p);
double tcL_t(double t);
double tcV_t(double t);
double tc_pt(double p, double t);
double tc_ph(double p, double h);
double tc_hs(double h, double s);
double x_ph(double p, double h);
double x_ps(double p, double s);
double vx_ph(double p, double h);
double vx_ps(double p, double s);
double pmelt_t(double t, int hint);
double psubl_t(double t);
